#!/bin/bash

echo "WARNING: This is script is experimental..."

# Get the path of /rsyn.
rsynPath="$( cd "$(dirname "$0")" ; pwd -P )"

# Go to rsyn directory
cd $rsynPath

# Create a backup.
tmp=$(mktemp -d)
echo "Creating a backup of /rsyn in $tmp..."
cp -r $rsynPath $tmp

git stash
git pull
git stash pop
git add .
git push

# Go back
cd -
